# Generated by Django 5.0.1 on 2024-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('E_Comm_app', '0002_delete_card_remove_cart_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
    ]
