# Generated by Django 5.0.2 on 2024-02-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('E_Comm_app', '0004_remove_card_user_id_remove_cart_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Category_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=300)),
                ('Product_Description', models.TextField(null=True)),
                ('Product_Image', models.ImageField(upload_to='photos')),
                ('Product_Quantity', models.IntegerField()),
                ('Product_Price', models.IntegerField()),
                ('Product_Status', models.CharField(choices=[('0', 'Available'), ('1', 'Not Avilable')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='photos')),
                ('Product_Image_dark', models.ImageField(null=True, upload_to='photos')),
                ('Discount_deals', models.CharField(choices=[('Get 20% off on all laptops and smartphones.', 'Get 20% off on all laptops and smartphones.'), ('Bundle offer: Buy a TV and soundbar together and save 15%.', 'Bundle offer: Buy a TV and soundbar together and save 15%.'), ('Stay Connected: Save 15% on all smartwatches.', 'Stay Connected: Save 15% on all smartwatches.'), ('Save $20 on your purchase!', 'Save $20 on your purchase!')], max_length=150)),
                ('Sale', models.IntegerField()),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Product_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=150)),
                ('Name', models.CharField(max_length=150)),
                ('Role', models.CharField(max_length=50, null=True)),
                ('User_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Address', models.TextField()),
                ('User_Gender', models.CharField(max_length=20)),
                ('User_DateofBirth', models.DateField(auto_now=True)),
                ('User_Image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=150)),
                ('Main_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Method', models.CharField(max_length=20)),
                ('Total_Amount', models.FloatField()),
                ('Oreder_Status', models.CharField(choices=[('0', 'Deliverd'), ('1', 'Pending')], max_length=10)),
                ('Cart_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.cart')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Product_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.product'),
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category_Name', models.CharField(max_length=200)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.sub_category'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Amount', models.IntegerField()),
                ('Payment_Status', models.CharField(choices=[('0', 'Success'), ('1', 'Failed')], max_length=15)),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.order')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Rating', models.IntegerField()),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.product')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Complain_Date', models.DateField()),
                ('Complain_Status', models.CharField(choices=[('0', 'Solved'), ('1', 'Pending')], max_length=20)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Name', models.CharField(max_length=30)),
                ('CVV', models.IntegerField()),
                ('Expiry_Date', models.DateField()),
                ('Card_Number', models.BigIntegerField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Date', models.DateField()),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.product')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
    ]
