# Generated by Django 5.0.2 on 2024-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='photos')),
                ('Discount_deals', models.CharField(choices=[('Get 20% off on all laptops and smartphones.', 'Get 20% off on all laptops and smartphones.'), ('Bundle offer: Buy a TV and soundbar together and save 15%.', 'Bundle offer: Buy a TV and soundbar together and save 15%.'), ('Stay Connected: Save 15% on all smartwatches.', 'Stay Connected: Save 15% on all smartwatches.'), ('Save $20 on your purchase!', 'Save $20 on your purchase!')], max_length=150)),
                ('Sale', models.IntegerField()),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Product_link', models.CharField(max_length=100)),
            ],
        ),
    ]
