# Generated by Django 5.0.2 on 2024-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0005_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Product_Image_dark',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
