# Generated by Django 5.0.2 on 2024-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cart_Status',
            field=models.CharField(choices=[('0', 'Confirm'), ('1', 'Pending')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='Total_Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(max_length=20),
        ),
    ]
