# Generated by Django 5.0.2 on 2024-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0008_cart_cart_status_cart_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Image',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image_1',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image_2',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image_3',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
