# Generated by Django 5.0.3 on 2024-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0009_remove_product_product_image_product_product_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(choices=[('Availbale', 'Available'), ('Unavailable', 'Unavailable')], max_length=20),
        ),
    ]
