# Generated by Django 5.0.2 on 2024-02-28 13:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0009_remove_product_product_image_product_product_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Offers',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20),
        ),
    ]
