# Generated by Django 5.0.3 on 2024-03-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Comm_app', '0011_alter_cart_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Store_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payment_Method',
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now=True)),
                ('Message', models.TextField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Comm_app.user')),
            ],
        ),
    ]
